package com.example.teamleaguebagit.pojos;
// Generated 24-may-2019 19:04:20 by Hibernate Tools 5.1.10.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

	private int idPartido;
	private Equipos equiposByIdVisitante;
	private Equipos equiposByIdLocal;
	private Date semana;
	private Set<Puntuaciones> puntuacioneses = new HashSet<Puntuaciones>(0);

	public Partidos() {
	}

	public Partidos(int idPartido, Equipos equiposByIdVisitante, Date semana) {
		this.idPartido = idPartido;
		this.equiposByIdVisitante = equiposByIdVisitante;
		this.semana = semana;
	}

	public Partidos(int idPartido, Equipos equiposByIdVisitante, Equipos equiposByIdLocal, Date semana,
			Set<Puntuaciones> puntuacioneses) {
		this.idPartido = idPartido;
		this.equiposByIdVisitante = equiposByIdVisitante;
		this.equiposByIdLocal = equiposByIdLocal;
		this.semana = semana;
		this.puntuacioneses = puntuacioneses;
	}

	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

	public Equipos getEquiposByIdVisitante() {
		return this.equiposByIdVisitante;
	}

	public void setEquiposByIdVisitante(Equipos equiposByIdVisitante) {
		this.equiposByIdVisitante = equiposByIdVisitante;
	}

	public Equipos getEquiposByIdLocal() {
		return this.equiposByIdLocal;
	}

	public void setEquiposByIdLocal(Equipos equiposByIdLocal) {
		this.equiposByIdLocal = equiposByIdLocal;
	}

	public Date getSemana() {
		return this.semana;
	}

	public void setSemana(Date semana) {
		this.semana = semana;
	}

	public Set<Puntuaciones> getPuntuacioneses() {
		return this.puntuacioneses;
	}

	public void setPuntuacioneses(Set<Puntuaciones> puntuacioneses) {
		this.puntuacioneses = puntuacioneses;
	}

}
