package com.example.teamleaguebagit.pojos;
// Generated 24-may-2019 19:04:20 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private String idUsuario;
	private String nombre;
	private String apellidos;
	private String correo;
	private Date fechaNacimiento;
	private int admin;
	private Set<EquiposUsuarios> equiposUsuarioses = new HashSet<EquiposUsuarios>(0);
	private PasswordUsuarios passwordUsuarios;
	private Set<Ligas> ligases = new HashSet<Ligas>(0);

	public Usuarios() {
	}

	public Usuarios(String idUsuario, String nombre, String apellidos, String correo, Date fechaNacimiento, int admin) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.correo = correo;
		this.fechaNacimiento = fechaNacimiento;
		this.admin = admin;
	}

	public Usuarios(String idUsuario, String nombre, String apellidos, String correo, Date fechaNacimiento, int admin,
			Set<EquiposUsuarios> equiposUsuarioses, PasswordUsuarios passwordUsuarios, Set<Ligas> ligases) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.correo = correo;
		this.fechaNacimiento = fechaNacimiento;
		this.admin = admin;
		this.equiposUsuarioses = equiposUsuarioses;
		this.passwordUsuarios = passwordUsuarios;
		this.ligases = ligases;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public int getAdmin() {
		return this.admin;
	}

	public void setAdmin(int admin) {
		this.admin = admin;
	}

	public Set<EquiposUsuarios> getEquiposUsuarioses() {
		return this.equiposUsuarioses;
	}

	public void setEquiposUsuarioses(Set<EquiposUsuarios> equiposUsuarioses) {
		this.equiposUsuarioses = equiposUsuarioses;
	}

	public PasswordUsuarios getPasswordUsuarios() {
		return this.passwordUsuarios;
	}

	public void setPasswordUsuarios(PasswordUsuarios passwordUsuarios) {
		this.passwordUsuarios = passwordUsuarios;
	}

	public Set<Ligas> getLigases() {
		return this.ligases;
	}

	public void setLigases(Set<Ligas> ligases) {
		this.ligases = ligases;
	}

}
