package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

	private String idEquipo;
	private String nombre;
	private String color;
	private String logo;
	private String campo;
	private Set<EquiposUsuarios> equiposUsuarioses = new HashSet<EquiposUsuarios>(0);
	private Set<Jugadores> jugadoreses = new HashSet<Jugadores>(0);
	private Set<Partidos> partidosesForIdVisitante = new HashSet<Partidos>(0);
	private Set<Partidos> partidosesForIdLocal = new HashSet<Partidos>(0);

	public Equipos() {
	}

	public Equipos(String idEquipo, String nombre, String color) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.color = color;
	}

	public Equipos(String idEquipo, String nombre, String color, String logo, String campo,
			Set<EquiposUsuarios> equiposUsuarioses, Set<Jugadores> jugadoreses, Set<Partidos> partidosesForIdVisitante,
			Set<Partidos> partidosesForIdLocal) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.color = color;
		this.logo = logo;
		this.campo = campo;
		this.equiposUsuarioses = equiposUsuarioses;
		this.jugadoreses = jugadoreses;
		this.partidosesForIdVisitante = partidosesForIdVisitante;
		this.partidosesForIdLocal = partidosesForIdLocal;
	}

	public String getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(String idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	public Set<EquiposUsuarios> getEquiposUsuarioses() {
		return this.equiposUsuarioses;
	}

	public void setEquiposUsuarioses(Set<EquiposUsuarios> equiposUsuarioses) {
		this.equiposUsuarioses = equiposUsuarioses;
	}

	public Set<Jugadores> getJugadoreses() {
		return this.jugadoreses;
	}

	public void setJugadoreses(Set<Jugadores> jugadoreses) {
		this.jugadoreses = jugadoreses;
	}

	public Set<Partidos> getPartidosesForIdVisitante() {
		return this.partidosesForIdVisitante;
	}

	public void setPartidosesForIdVisitante(Set<Partidos> partidosesForIdVisitante) {
		this.partidosesForIdVisitante = partidosesForIdVisitante;
	}

	public Set<Partidos> getPartidosesForIdLocal() {
		return this.partidosesForIdLocal;
	}

	public void setPartidosesForIdLocal(Set<Partidos> partidosesForIdLocal) {
		this.partidosesForIdLocal = partidosesForIdLocal;
	}

}
