package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EquiposUsuarios generated by hbm2java
 */
public class EquiposUsuarios implements java.io.Serializable {

	private int idEquipo;
	private Equipos equipos;
	private Ligas ligas;
	private Usuarios usuarios;
	private String nombreEquipo;
	private int dinero;
	private Set<Plantillas> plantillases = new HashSet<Plantillas>(0);

	public EquiposUsuarios() {
	}

	public EquiposUsuarios(int idEquipo, Equipos equipos, Ligas ligas, Usuarios usuarios, String nombreEquipo,
			int dinero) {
		this.idEquipo = idEquipo;
		this.equipos = equipos;
		this.ligas = ligas;
		this.usuarios = usuarios;
		this.nombreEquipo = nombreEquipo;
		this.dinero = dinero;
	}

	public EquiposUsuarios(int idEquipo, Equipos equipos, Ligas ligas, Usuarios usuarios, String nombreEquipo,
			int dinero, Set<Plantillas> plantillases) {
		this.idEquipo = idEquipo;
		this.equipos = equipos;
		this.ligas = ligas;
		this.usuarios = usuarios;
		this.nombreEquipo = nombreEquipo;
		this.dinero = dinero;
		this.plantillases = plantillases;
	}

	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public Ligas getLigas() {
		return this.ligas;
	}

	public void setLigas(Ligas ligas) {
		this.ligas = ligas;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreEquipo() {
		return this.nombreEquipo;
	}

	public void setNombreEquipo(String nombreEquipo) {
		this.nombreEquipo = nombreEquipo;
	}

	public int getDinero() {
		return this.dinero;
	}

	public void setDinero(int dinero) {
		this.dinero = dinero;
	}

	public Set<Plantillas> getPlantillases() {
		return this.plantillases;
	}

	public void setPlantillases(Set<Plantillas> plantillases) {
		this.plantillases = plantillases;
	}

}
