package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private String idJugador;
	private Equipos equipos;
	private String nombre;
	private String apellido;
	private String dorsal;
	private int lesionado;
	private int precioMercado;
	private String posicion;
	private int estrellas;
	private int puntosTotales;
	private byte[] imagen;
	private int media;
	private Set<Plantillas> plantillases = new HashSet<Plantillas>(0);
	private Set<Puntuaciones> puntuacioneses = new HashSet<Puntuaciones>(0);

	public Jugadores() {
	}

	public Jugadores(String idJugador, String nombre, String apellido, String dorsal, int lesionado, int precioMercado,
			String posicion, int estrellas, int puntosTotales, int media) {
		this.idJugador = idJugador;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dorsal = dorsal;
		this.lesionado = lesionado;
		this.precioMercado = precioMercado;
		this.posicion = posicion;
		this.estrellas = estrellas;
		this.puntosTotales = puntosTotales;
		this.media = media;
	}

	public Jugadores(String idJugador, Equipos equipos, String nombre, String apellido, String dorsal, int lesionado,
			int precioMercado, String posicion, int estrellas, int puntosTotales, byte[] imagen, int media,
			Set<Plantillas> plantillases, Set<Puntuaciones> puntuacioneses) {
		this.idJugador = idJugador;
		this.equipos = equipos;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dorsal = dorsal;
		this.lesionado = lesionado;
		this.precioMercado = precioMercado;
		this.posicion = posicion;
		this.estrellas = estrellas;
		this.puntosTotales = puntosTotales;
		this.imagen = imagen;
		this.media = media;
		this.plantillases = plantillases;
		this.puntuacioneses = puntuacioneses;
	}

	public String getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(String idJugador) {
		this.idJugador = idJugador;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(String dorsal) {
		this.dorsal = dorsal;
	}

	public int getLesionado() {
		return this.lesionado;
	}

	public void setLesionado(int lesionado) {
		this.lesionado = lesionado;
	}

	public int getPrecioMercado() {
		return this.precioMercado;
	}

	public void setPrecioMercado(int precioMercado) {
		this.precioMercado = precioMercado;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public int getEstrellas() {
		return this.estrellas;
	}

	public void setEstrellas(int estrellas) {
		this.estrellas = estrellas;
	}

	public int getPuntosTotales() {
		return this.puntosTotales;
	}

	public void setPuntosTotales(int puntosTotales) {
		this.puntosTotales = puntosTotales;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public int getMedia() {
		return this.media;
	}

	public void setMedia(int media) {
		this.media = media;
	}

	public Set<Plantillas> getPlantillases() {
		return this.plantillases;
	}

	public void setPlantillases(Set<Plantillas> plantillases) {
		this.plantillases = plantillases;
	}

	public Set<Puntuaciones> getPuntuacioneses() {
		return this.puntuacioneses;
	}

	public void setPuntuacioneses(Set<Puntuaciones> puntuacioneses) {
		this.puntuacioneses = puntuacioneses;
	}

}
