package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

/**
 * PasswordLigas generated by hbm2java
 */
public class PasswordLigas implements java.io.Serializable {

	private String idLiga;
	private Ligas ligas;
	private String password;

	public PasswordLigas() {
	}

	public PasswordLigas(Ligas ligas, String password) {
		this.ligas = ligas;
		this.password = password;
	}

	public String getIdLiga() {
		return this.idLiga;
	}

	public void setIdLiga(String idLiga) {
		this.idLiga = idLiga;
	}

	public Ligas getLigas() {
		return this.ligas;
	}

	public void setLigas(Ligas ligas) {
		this.ligas = ligas;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
