package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

/**
 * PuntuacionesId generated by hbm2java
 */
public class PuntuacionesId implements java.io.Serializable {

	private String idJugador;
	private int idPartido;

	public PuntuacionesId() {
	}

	public PuntuacionesId(String idJugador, int idPartido) {
		this.idJugador = idJugador;
		this.idPartido = idPartido;
	}

	public String getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(String idJugador) {
		this.idJugador = idJugador;
	}

	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntuacionesId))
			return false;
		PuntuacionesId castOther = (PuntuacionesId) other;

		return ((this.getIdJugador() == castOther.getIdJugador()) || (this.getIdJugador() != null
				&& castOther.getIdJugador() != null && this.getIdJugador().equals(castOther.getIdJugador())))
				&& (this.getIdPartido() == castOther.getIdPartido());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdJugador() == null ? 0 : this.getIdJugador().hashCode());
		result = 37 * result + this.getIdPartido();
		return result;
	}

}
