package com.example.myapplication;
// Generated 09-may-2019 19:56:04 by Hibernate Tools 5.1.10.Final

/**
 * Puntuaciones generated by hbm2java
 */
public class Puntuaciones implements java.io.Serializable {

	private PuntuacionesId id;
	private Jugadores jugadores;
	private Partidos partidos;
	private int puntuacion;

	public Puntuaciones() {
	}

	public Puntuaciones(PuntuacionesId id, Jugadores jugadores, Partidos partidos, int puntuacion) {
		this.id = id;
		this.jugadores = jugadores;
		this.partidos = partidos;
		this.puntuacion = puntuacion;
	}

	public PuntuacionesId getId() {
		return this.id;
	}

	public void setId(PuntuacionesId id) {
		this.id = id;
	}

	public Jugadores getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Jugadores jugadores) {
		this.jugadores = jugadores;
	}

	public Partidos getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Partidos partidos) {
		this.partidos = partidos;
	}

	public int getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(int puntuacion) {
		this.puntuacion = puntuacion;
	}

}
